name: Run Tests upon PullRequest
on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Run Test Cases
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}-${{ hashFiles('**/buildSrc/src/main/kotlin/**/*.kt') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Execute test cases
        run: ./gradlew test

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: ./*/build/reports/tests/

